apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: kafka-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer-service:latest
          imagePullPolicy: Never   # usa imagem local no Minikube
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
