apiVersion: v1
kind: Service
metadata:   # Parte 1: metadata for service
  name: nginx-service
spec:       # Parte 2: specification for service
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80