apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    # Pod Blueprint
    spec:
      containers:
      - name: mongodb         # Container name
        image: mongo:latest   # Container image
        ports:
        - containerPort: 27017 # MongoDB default port
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb    # mesmo nome listado em matchLabels do Deployment
  ports:
  - protocol: TCP
    port: 27017         # Service port (exposta)
    targetPort: 27017   # Container port